baseurl      = "/"
title        = "Takeover by seb.d"
languageCode = "en-us"
theme        = "hello-friend-ng_pers"
paginate     = 20

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "Portfolio of Sebastian Dugudae"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "Home page"
  keywords = "homepage, blog"
  images = [""]

[languages]
  [languages.en]
    # in tab
    title = "Takeover by seb.d"
    subtitle = "Portfolio of Sebastian Dugudae"
    keywords = ""
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "home"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"
    
  [[params.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/sebastian-dugudae/"
    
  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/_sebd"
    
  [[params.social]]
    name = "hackerone"
    url = "https://hackerone.com/sebd?type=user"
  
  [[params.social]]
    name = "github"
    url = "https://github.com/sebd0"
    
  [[params.social]]
    name = "case"
    url = "https://bugcrowd.com/sebd"
  
  [[params.social]]
    name = "case"
    url = "https://app.intigriti.com/researcher/profile/sebd"
  
  [[params.social]]
    name = "case"
    url = "https://app.hackthebox.eu/profile/76681"
    
  # And you can even create generic menu
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "https://medium.com/@seb.d"
    
  [[menu.main]]
    identifier = "achievements"
    name       = "Achievements"
    url        = "/achievements"
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about"
    
